config/routes.rb
Rails.application.routes.draw do
  
  # Root
  root to: 'visitors#index', as: :home

  # Devise
  devise_for :users
  devise_for :admin_users

  # User
  scope module: 'user', as: :user do
    namespace :counsel do
      resources :votes
    end # For User
    namespace :counsel do
      resources :answer_requests
    end # For User
    namespace :counsel do
      resources :answers
    end # For User
    namespace :counsel do
      resources :question_categories
    end # For User
    namespace :counsel do
      resources :questions
    end # For User
    namespace :counsel do
      resources :categories
    end # For User
    resources :global_settings # For User
    resources :reviews # For User
    resources :payment_requests # For User
    resources :customer_payments # For User
    resources :quotes # For User
    resources :carts # For User
    resources :scopes # For User
    namespace :service_flow do
      resources :user_answer_choices
    end # For User
    resources :user_processes # For User
    resources :professional_fees # For User
    resources :professional_sub_services # For User
    resources :professional_services # For User
    resources :professional_profile_edits # For User
    resources :professionals # For User
    namespace :service_flow do
      resources :answer_choices
    end # For User
    namespace :service_flow do
      resources :questions
    end # For User
    resources :scenarios # For User
    resources :sub_services # For User
    resources :services # For User
    resources :locations # For User
    get 'dashboard', to: 'dashboard#index', as: :dashboard
  end

  # Admin
  namespace :admin do
    namespace :counsel do
      resources :votes
    end # For Admin
    namespace :counsel do
      resources :answer_requests
    end # For Admin
    namespace :counsel do
      resources :answers
    end # For Admin
    namespace :counsel do
      resources :question_categories
    end # For Admin
    namespace :counsel do
      resources :questions
    end # For Admin
    namespace :counsel do
      resources :categories
    end # For Admin
    resources :global_settings # For Admin
    resources :reviews # For Admin
    resources :payment_requests # For Admin
    resources :customer_payments # For Admin
    resources :quotes # For Admin
    resources :carts # For Admin
    resources :scopes # For Admin
    namespace :service_flow do
      resources :user_answer_choices
    end # For Admin
    resources :user_processes # For Admin
    resources :professional_fees # For Admin
    resources :professional_sub_services # For Admin
    resources :professional_services # For Admin
    resources :professional_profile_edits # For Admin
    resources :professionals # For Admin
    namespace :service_flow do
      resources :answer_choices
    end # For Admin
    namespace :service_flow do
      resources :questions
    end # For Admin
    resources :scenarios # For Admin
    resources :sub_services # For Admin
    resources :services # For Admin
    resources :locations # For Admin
    get 'dashboard', to: 'dashboard#index', as: :dashboard
  end

end

app/models/scope.rb
class Scope < ApplicationRecord
  belongs_to :user_process
  belongs_to :professional
end

app/controllers/admin/scopes_controller.rb
module Admin
  class ScopesController < ApplicationController
    before_action :set_scope, only: [:show, :edit, :update, :destroy]
    load_and_authorize_resource

    # GET /admin/scopes
    # GET /admin/scopes.json
    def index
      @scopes = Scope.all
    end

    # GET /admin/scopes/1
    # GET /admin/scopes/1.json
    def show
    end

    # GET /admin/scopes/new
    def new
      @scope = Scope.new
    end

    # GET /admin/scopes/1/edit
    def edit
    end

    # POST /admin/scopes
    # POST /admin/scopes.json
    def create
      @scope = Scope.new(scope_params)

      respond_to do |format|
        if @scope.save
          format.html { redirect_to admin_scopes_url, notice: 'Scope was successfully created.' }
          format.json { render :show, status: :created, location: admin_scopes_url }
        else
          format.html { render :new }
          format.json { render json: @scope.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /admin/scopes/1
    # PATCH/PUT /admin/scopes/1.json
    def update
      respond_to do |format|
        if @scope.update(scope_params)
          format.html { redirect_to [:admin, @scope], notice: 'Scope was successfully updated.' }
          format.json { render :show, status: :ok, location: [:admin, @scope] }
        else
          format.html { render :edit }
          format.json { render json: @scope.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /admin/scopes/1
    # DELETE /admin/scopes/1.json
    def destroy
      @scope.destroy
      respond_to do |format|
        format.html { redirect_to admin_scopes_url, notice: 'Scope was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_scope
        @scope = Scope.where(id: params[:id]).first
        return invalid_access_flash_redirect_and_return if @scope.blank?
      end

      # Only allow a trusted parameter "white list" through.
      def scope_params
        default_values = {}
        params.require(:scope).permit(:name, :user_process_id, :professional_id, :inclusions, :exclusions, :documents, :deliverables, :status, :started_at, :closed_at, :expected_duration).merge(default_values)
      end
  end
end

app/controllers/user/scopes_controller.rb
module User
  class ScopesController < ApplicationController
    before_action :set_scope, only: [:show, :edit, :update, :destroy]
    load_and_authorize_resource

    # GET /user/scopes
    # GET /user/scopes.json
    def index
      @scopes = Scope.where(user_id: current_user.id)
    end

    # GET /user/scopes/1
    # GET /user/scopes/1.json
    def show
    end

    # GET /user/scopes/new
    def new
      @scope = Scope.new
    end

    # GET /user/scopes/1/edit
    def edit
    end

    # POST /user/scopes
    # POST /user/scopes.json
    def create
      @scope = Scope.new(scope_params)
      respond_to do |format|
        if @scope.save
          format.html { redirect_to user_scopes_url, notice: 'Scope was successfully created.' }
          format.json { render :show, status: :created, location: user_scopes_url }
        else
          format.html { render :new }
          format.json { render json: @scope.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /user/scopes/1
    # PATCH/PUT /user/scopes/1.json
    def update
      respond_to do |format|
        if @scope.update(scope_params)
          format.html { redirect_to [:user, @scope], notice: 'Scope was successfully updated.' }
          format.json { render :show, status: :ok, location: [:user, @scope] }
        else
          format.html { render :edit }
          format.json { render json: @scope.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /user/scopes/1
    # DELETE /user/scopes/1.json
    def destroy
      @scope.destroy
      respond_to do |format|
        format.html { redirect_to user_scopes_url, notice: 'Scope was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_scope
        @scope = Scope.where(id: params[:id], user_id: current_user.id).first
        return invalid_access_flash_redirect_and_return if @scope.blank?
      end

      # Only allow a trusted parameter "white list" through.
      def scope_params
        default_values = {user_id: current_user.id}
        params.require(:scope).permit(:name, :user_process_id, :professional_id, :inclusions, :exclusions, :documents, :deliverables, :status, :started_at, :closed_at, :expected_duration).merge(default_values)
      end
  end
end

app/views/admin/scopes/_form.html.erb
<%= simple_form_for([:admin, @scope], wrapper: :horizontal_form, html: {class: "form-horizontal"})  do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.association :user_process %>
    <%= f.association :professional %>
    <%= f.input :inclusions %>
    <%= f.input :exclusions %>
    <%= f.input :documents %>
    <%= f.input :deliverables %>
    <%= f.input :status %>
    <%= f.input :started_at %>
    <%= f.input :closed_at %>
    <%= f.input :expected_duration %>
  </div>

  <div class="form-actions text-center">
    <%= button_tag "Save", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/admin/scopes/edit.html.erb
<% content_for :breadcrumb do %>
  <%= breadcrumb_bar_new do %>
    <%= breadcrumb_item(link: admin_scopes_path, text: 'Scopes') %>
    <%= breadcrumb_item(link: admin_scope_path(@scope), text: @scope.name) %>
    <%= breadcrumb_item(text: 'Edit') %>
  <% end %>
<% end %>

<%= new_page_heading('Editing Scope') %>
<%= full_width_box_wrapper do %>
  <%= box_content_only do %>
    <%= render 'form' %>
  <% end %>
<% end %>

app/views/admin/scopes/index.html.erb
<% content_for :breadcrumb do %>
  <%= breadcrumb_bar_new do %>
    <%= breadcrumb_item(text: 'Scopes') %>
  <% end %>
<% end %>

<%= new_page_heading do %>
  Listing Scopes
  <% if can? :create, Scope %>
    <span class="pull-right">
      <%= link_to 'New Scope', new_admin_scope_path, class: 'btn btn-primary' %>
    </span>
  <% end %>
<% end %>

<%= full_width_box_wrapper do %>
  <%= box_content_only do %>
    <div class="table-responsive">
      <%= page_datatable do %>
        <thead>
          <tr>
            <th>Name</th>
            <th>User process</th>
            <th>Professional</th>
            <th>Inclusions</th>
            <th>Exclusions</th>
            <th>Documents</th>
            <th>Deliverables</th>
            <th>Status</th>
            <th>Started at</th>
            <th>Closed at</th>
            <th>Expected duration</th>
            <th>Actions</th>
          </tr>
        </thead>

        <tbody>
          <% @scopes.each do |scope| %>
            <tr>
              <td><%= link_to scope.name, [:admin, scope], class: 'row-link' %></td>
              <td><%= scope.user_process.try(:name) %></td>
              <td><%= scope.professional.try(:name) %></td>
              <td><%= scope.inclusions %></td>
              <td><%= scope.exclusions %></td>
              <td><%= scope.documents %></td>
              <td><%= scope.deliverables %></td>
              <td><%= scope.status %></td>
              <td><%= scope.started_at %></td>
              <td><%= scope.closed_at %></td>
              <td><%= scope.expected_duration %></td>
              <td>
                <% if can? :update, scope %>
                  <%= link_to 'Edit', edit_admin_scope_path(scope) %>
                <% end %>
                <% if false and can? :destroy, scope %> |
                  <%= link_to 'Destroy', [:admin, scope], method: :delete, data: { confirm: 'Are you sure?' } %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      <% end %>
    </div>
  <% end %>
<% end %>

<% content_for :javascript do %>
<script>  
  $('#dataTables-example').DataTable({
    pageLength: 25
  });
</script>
<% end %>

app/views/admin/scopes/new.html.erb
<% content_for :breadcrumb do %>
  <%= breadcrumb_bar_new do %>
    <%= breadcrumb_item(link: admin_scopes_path, text: 'Scopes') %>
    <%= breadcrumb_item(text: 'New') %>
  <% end %>
<% end %>

<%= new_page_heading('New Scope') %>
<%= full_width_box_wrapper do %>
  <%= box_content_only do %>
    <%= render 'form' %>
  <% end %>
<% end %>

app/views/admin/scopes/show.html.erb
<% content_for :breadcrumb do %>
  <%= breadcrumb_bar_new do %>
    <%= breadcrumb_item(link: admin_scopes_path, text: 'Scopes') %>
    <%= breadcrumb_item(text: @scope.name) %>
  <% end %>
<% end %>

<%= new_page_heading do %>
  <%= @scope.name %>
  <% if can? :update, @scope %>
    <span class="pull-right">
      <%= link_to 'Edit', edit_admin_scope_path, class: 'btn btn-primary btn-outline' %>
    </span>
  <% end %>
<% end %>

<%= full_width_box_wrapper do %>
  <%= box_content_only do %>
    <p class="row">
      <strong class="col-md-3 text-right">Name</strong>
      <span class="col-md-9"><%= @scope.name %></span>
    </p>
    <p class="row">
      <strong class="col-md-3 text-right">User process</strong>
      <span class="col-md-9"><%= @scope.user_process.try(:name) %></span>
    </p>
    <p class="row">
      <strong class="col-md-3 text-right">Professional</strong>
      <span class="col-md-9"><%= @scope.professional.try(:name) %></span>
    </p>
    <p class="row">
      <strong class="col-md-3 text-right">Inclusions</strong>
      <span class="col-md-9"><%= @scope.inclusions %></span>
    </p>
    <p class="row">
      <strong class="col-md-3 text-right">Exclusions</strong>
      <span class="col-md-9"><%= @scope.exclusions %></span>
    </p>
    <p class="row">
      <strong class="col-md-3 text-right">Documents</strong>
      <span class="col-md-9"><%= @scope.documents %></span>
    </p>
    <p class="row">
      <strong class="col-md-3 text-right">Deliverables</strong>
      <span class="col-md-9"><%= @scope.deliverables %></span>
    </p>
    <p class="row">
      <strong class="col-md-3 text-right">Status</strong>
      <span class="col-md-9"><%= @scope.status %></span>
    </p>
    <p class="row">
      <strong class="col-md-3 text-right">Started at</strong>
      <span class="col-md-9"><%= @scope.started_at %></span>
    </p>
    <p class="row">
      <strong class="col-md-3 text-right">Closed at</strong>
      <span class="col-md-9"><%= @scope.closed_at %></span>
    </p>
    <p class="row">
      <strong class="col-md-3 text-right">Expected duration</strong>
      <span class="col-md-9"><%= @scope.expected_duration %></span>
    </p>
  <% end -%>
<% end -%>