config/routes.rb
Rails.application.routes.draw do
  
  # Root
  root to: 'visitors#index', as: :home

  # Devise
  devise_for :users
  devise_for :admin_users

  # User
  scope module: 'user', as: :user do
    namespace :counsel do
      resources :votes
    end # For User
    namespace :counsel do
      resources :answer_requests
    end # For User
    namespace :counsel do
      resources :answers
    end # For User
    namespace :counsel do
      resources :question_categories
    end # For User
    namespace :counsel do
      resources :questions
    end # For User
    namespace :counsel do
      resources :categories
    end # For User
    resources :global_settings # For User
    resources :reviews # For User
    resources :payment_requests # For User
    resources :customer_payments # For User
    resources :quotes # For User
    resources :carts # For User
    resources :scopes # For User
    namespace :service_flow do
      resources :user_answer_choices
    end # For User
    resources :user_processes # For User
    resources :professional_fees # For User
    resources :professional_sub_services # For User
    resources :professional_services # For User
    resources :professional_profile_edits # For User
    resources :professionals # For User
    namespace :service_flow do
      resources :answer_choices
    end # For User
    namespace :service_flow do
      resources :questions
    end # For User
    resources :scenarios # For User
    resources :sub_services # For User
    resources :services # For User
    resources :locations # For User
    get 'dashboard', to: 'dashboard#index', as: :dashboard
  end

  # Admin
  namespace :admin do
    namespace :counsel do
      resources :votes
    end # For Admin
    namespace :counsel do
      resources :answer_requests
    end # For Admin
    namespace :counsel do
      resources :answers
    end # For Admin
    namespace :counsel do
      resources :question_categories
    end # For Admin
    namespace :counsel do
      resources :questions
    end # For Admin
    namespace :counsel do
      resources :categories
    end # For Admin
    resources :global_settings # For Admin
    resources :reviews # For Admin
    resources :payment_requests # For Admin
    resources :customer_payments # For Admin
    resources :quotes # For Admin
    resources :carts # For Admin
    resources :scopes # For Admin
    namespace :service_flow do
      resources :user_answer_choices
    end # For Admin
    resources :user_processes # For Admin
    resources :professional_fees # For Admin
    resources :professional_sub_services # For Admin
    resources :professional_services # For Admin
    resources :professional_profile_edits # For Admin
    resources :professionals # For Admin
    namespace :service_flow do
      resources :answer_choices
    end # For Admin
    namespace :service_flow do
      resources :questions
    end # For Admin
    resources :scenarios # For Admin
    resources :sub_services # For Admin
    resources :services # For Admin
    resources :locations # For Admin
    get 'dashboard', to: 'dashboard#index', as: :dashboard
  end

end

app/models/service_flow.rb
module ServiceFlow
  def self.table_name_prefix
    'service_flow_'
  end
end

app/models/service_flow/answer_choice.rb
class ServiceFlow::AnswerChoice < ApplicationRecord
  belongs_to :question
end

app/models/service_flow/question.rb
class ServiceFlow::Question < ApplicationRecord
end

app/models/service_flow/user_answer_choice.rb
class ServiceFlow::UserAnswerChoice < ApplicationRecord
  belongs_to :user
  belongs_to :answer_choice
  belongs_to :user_process
end

app/controllers/admin/service_flow/answer_choices_controller.rb
module Admin
  class ServiceFlow::AnswerChoicesController < ApplicationController
    before_action :set_service_flow_answer_choice, only: [:show, :edit, :update, :destroy]
    load_and_authorize_resource

    # GET /admin/service_flow/answer_choices
    # GET /admin/service_flow/answer_choices.json
    def index
      @service_flow_answer_choices = ::ServiceFlow::AnswerChoice.all
    end

    # GET /admin/service_flow/answer_choices/1
    # GET /admin/service_flow/answer_choices/1.json
    def show
    end

    # GET /admin/service_flow/answer_choices/new
    def new
      @service_flow_answer_choice = ::ServiceFlow::AnswerChoice.new
    end

    # GET /admin/service_flow/answer_choices/1/edit
    def edit
    end

    # POST /admin/service_flow/answer_choices
    # POST /admin/service_flow/answer_choices.json
    def create
      @service_flow_answer_choice = ::ServiceFlow::AnswerChoice.new(service_flow_answer_choice_params)

      respond_to do |format|
        if @service_flow_answer_choice.save
          format.html { redirect_to admin_service_flow_answer_choices_url, notice: 'Answer choice was successfully created.' }
          format.json { render :show, status: :created, location: admin_service_flow_answer_choices_url }
        else
          format.html { render :new }
          format.json { render json: @service_flow_answer_choice.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /admin/service_flow/answer_choices/1
    # PATCH/PUT /admin/service_flow/answer_choices/1.json
    def update
      respond_to do |format|
        if @service_flow_answer_choice.update(service_flow_answer_choice_params)
          format.html { redirect_to [:admin, @service_flow_answer_choice], notice: 'Answer choice was successfully updated.' }
          format.json { render :show, status: :ok, location: [:admin, @service_flow_answer_choice] }
        else
          format.html { render :edit }
          format.json { render json: @service_flow_answer_choice.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /admin/service_flow/answer_choices/1
    # DELETE /admin/service_flow/answer_choices/1.json
    def destroy
      @service_flow_answer_choice.destroy
      respond_to do |format|
        format.html { redirect_to admin_service_flow_answer_choices_url, notice: 'Answer choice was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_service_flow_answer_choice
        @service_flow_answer_choice = ::ServiceFlow::AnswerChoice.where(id: params[:id]).first
        return invalid_access_flash_redirect_and_return if @service_flow_answer_choice.blank?
      end

      # Only allow a trusted parameter "white list" through.
      def service_flow_answer_choice_params
        default_values = {}
        params.require(:service_flow_answer_choice).permit(:question_id, :answer, :position, :next_questions).merge(default_values)
      end
  end
end

app/controllers/admin/service_flow/questions_controller.rb
module Admin
  class ServiceFlow::QuestionsController < ApplicationController
    before_action :set_service_flow_question, only: [:show, :edit, :update, :destroy]
    load_and_authorize_resource

    # GET /admin/service_flow/questions
    # GET /admin/service_flow/questions.json
    def index
      @service_flow_questions = ::ServiceFlow::Question.all
    end

    # GET /admin/service_flow/questions/1
    # GET /admin/service_flow/questions/1.json
    def show
    end

    # GET /admin/service_flow/questions/new
    def new
      @service_flow_question = ::ServiceFlow::Question.new
    end

    # GET /admin/service_flow/questions/1/edit
    def edit
    end

    # POST /admin/service_flow/questions
    # POST /admin/service_flow/questions.json
    def create
      @service_flow_question = ::ServiceFlow::Question.new(service_flow_question_params)

      respond_to do |format|
        if @service_flow_question.save
          format.html { redirect_to admin_service_flow_questions_url, notice: 'Question was successfully created.' }
          format.json { render :show, status: :created, location: admin_service_flow_questions_url }
        else
          format.html { render :new }
          format.json { render json: @service_flow_question.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /admin/service_flow/questions/1
    # PATCH/PUT /admin/service_flow/questions/1.json
    def update
      respond_to do |format|
        if @service_flow_question.update(service_flow_question_params)
          format.html { redirect_to [:admin, @service_flow_question], notice: 'Question was successfully updated.' }
          format.json { render :show, status: :ok, location: [:admin, @service_flow_question] }
        else
          format.html { render :edit }
          format.json { render json: @service_flow_question.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /admin/service_flow/questions/1
    # DELETE /admin/service_flow/questions/1.json
    def destroy
      @service_flow_question.destroy
      respond_to do |format|
        format.html { redirect_to admin_service_flow_questions_url, notice: 'Question was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_service_flow_question
        @service_flow_question = ::ServiceFlow::Question.where(id: params[:id]).first
        return invalid_access_flash_redirect_and_return if @service_flow_question.blank?
      end

      # Only allow a trusted parameter "white list" through.
      def service_flow_question_params
        default_values = {}
        params.require(:service_flow_question).permit(:question, :question_type, :parent).merge(default_values)
      end
  end
end

app/controllers/admin/service_flow/user_answer_choices_controller.rb
module Admin
  class ServiceFlow::UserAnswerChoicesController < ApplicationController
    before_action :set_service_flow_user_answer_choice, only: [:show, :edit, :update, :destroy]
    load_and_authorize_resource

    # GET /admin/service_flow/user_answer_choices
    # GET /admin/service_flow/user_answer_choices.json
    def index
      @service_flow_user_answer_choices = ::ServiceFlow::UserAnswerChoice.all
    end

    # GET /admin/service_flow/user_answer_choices/1
    # GET /admin/service_flow/user_answer_choices/1.json
    def show
    end

    # GET /admin/service_flow/user_answer_choices/new
    def new
      @service_flow_user_answer_choice = ::ServiceFlow::UserAnswerChoice.new
    end

    # GET /admin/service_flow/user_answer_choices/1/edit
    def edit
    end

    # POST /admin/service_flow/user_answer_choices
    # POST /admin/service_flow/user_answer_choices.json
    def create
      @service_flow_user_answer_choice = ::ServiceFlow::UserAnswerChoice.new(service_flow_user_answer_choice_params)

      respond_to do |format|
        if @service_flow_user_answer_choice.save
          format.html { redirect_to admin_service_flow_user_answer_choices_url, notice: 'User answer choice was successfully created.' }
          format.json { render :show, status: :created, location: admin_service_flow_user_answer_choices_url }
        else
          format.html { render :new }
          format.json { render json: @service_flow_user_answer_choice.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /admin/service_flow/user_answer_choices/1
    # PATCH/PUT /admin/service_flow/user_answer_choices/1.json
    def update
      respond_to do |format|
        if @service_flow_user_answer_choice.update(service_flow_user_answer_choice_params)
          format.html { redirect_to [:admin, @service_flow_user_answer_choice], notice: 'User answer choice was successfully updated.' }
          format.json { render :show, status: :ok, location: [:admin, @service_flow_user_answer_choice] }
        else
          format.html { render :edit }
          format.json { render json: @service_flow_user_answer_choice.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /admin/service_flow/user_answer_choices/1
    # DELETE /admin/service_flow/user_answer_choices/1.json
    def destroy
      @service_flow_user_answer_choice.destroy
      respond_to do |format|
        format.html { redirect_to admin_service_flow_user_answer_choices_url, notice: 'User answer choice was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_service_flow_user_answer_choice
        @service_flow_user_answer_choice = ::ServiceFlow::UserAnswerChoice.where(id: params[:id]).first
        return invalid_access_flash_redirect_and_return if @service_flow_user_answer_choice.blank?
      end

      # Only allow a trusted parameter "white list" through.
      def service_flow_user_answer_choice_params
        default_values = {}
        params.require(:service_flow_user_answer_choice).permit(:user_id, :answer_choice_id, :user_process_id).merge(default_values)
      end
  end
end

app/controllers/user/service_flow/answer_choices_controller.rb
module User
  class ServiceFlow::AnswerChoicesController < ApplicationController
    before_action :set_service_flow_answer_choice, only: [:show, :edit, :update, :destroy]
    load_and_authorize_resource

    # GET /user/service_flow/answer_choices
    # GET /user/service_flow/answer_choices.json
    def index
      @service_flow_answer_choices = ::ServiceFlow::AnswerChoice.where(user_id: current_user.id)
    end

    # GET /user/service_flow/answer_choices/1
    # GET /user/service_flow/answer_choices/1.json
    def show
    end

    # GET /user/service_flow/answer_choices/new
    def new
      @service_flow_answer_choice = ::ServiceFlow::AnswerChoice.new
    end

    # GET /user/service_flow/answer_choices/1/edit
    def edit
    end

    # POST /user/service_flow/answer_choices
    # POST /user/service_flow/answer_choices.json
    def create
      @service_flow_answer_choice = ::ServiceFlow::AnswerChoice.new(service_flow_answer_choice_params)
      respond_to do |format|
        if @service_flow_answer_choice.save
          format.html { redirect_to user_service_flow_answer_choices_url, notice: 'Answer choice was successfully created.' }
          format.json { render :show, status: :created, location: user_service_flow_answer_choices_url }
        else
          format.html { render :new }
          format.json { render json: @service_flow_answer_choice.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /user/service_flow/answer_choices/1
    # PATCH/PUT /user/service_flow/answer_choices/1.json
    def update
      respond_to do |format|
        if @service_flow_answer_choice.update(service_flow_answer_choice_params)
          format.html { redirect_to [:user, @service_flow_answer_choice], notice: 'Answer choice was successfully updated.' }
          format.json { render :show, status: :ok, location: [:user, @service_flow_answer_choice] }
        else
          format.html { render :edit }
          format.json { render json: @service_flow_answer_choice.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /user/service_flow/answer_choices/1
    # DELETE /user/service_flow/answer_choices/1.json
    def destroy
      @service_flow_answer_choice.destroy
      respond_to do |format|
        format.html { redirect_to user_service_flow_answer_choices_url, notice: 'Answer choice was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_service_flow_answer_choice
        @service_flow_answer_choice = ::ServiceFlow::AnswerChoice.where(id: params[:id], user_id: current_user.id).first
        return invalid_access_flash_redirect_and_return if @service_flow_answer_choice.blank?
      end

      # Only allow a trusted parameter "white list" through.
      def service_flow_answer_choice_params
        default_values = {user_id: current_user.id}
        params.require(:service_flow_answer_choice).permit(:question_id, :answer, :position, :next_questions).merge(default_values)
      end
  end
end

app/views/admin/service_flow/user_answer_choices/_form.html.erb
<%= simple_form_for([:admin, @service_flow_user_answer_choice], wrapper: :horizontal_form, html: {class: "form-horizontal"})  do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :user %>
    <%= f.association :answer_choice %>
    <%= f.association :user_process %>
  </div>

  <div class="form-actions text-center">
    <%= button_tag "Save", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/admin/service_flow/user_answer_choices/edit.html.erb
<% content_for :breadcrumb do %>
  <%= breadcrumb_bar_new do %>
    <%= breadcrumb_item(link: admin_service_flow_user_answer_choices_path, text: 'Service Flow User Answer Choices') %>
    <%= breadcrumb_item(link: admin_service_flow_user_answer_choice_path(@service_flow_user_answer_choice), text: 'Service Flow User Answer Choice') %>
    <%= breadcrumb_item(text: 'Edit') %>
  <% end %>
<% end %>

<%= new_page_heading('Editing Service Flow User Answer Choice') %>
<%= full_width_box_wrapper do %>
  <%= box_content_only do %>
    <%= render 'form' %>
  <% end %>
<% end %>

app/views/admin/service_flow/user_answer_choices/index.html.erb
<% content_for :breadcrumb do %>
  <%= breadcrumb_bar_new do %>
    <%= breadcrumb_item(text: 'Service Flow User Answer Choices') %>
  <% end %>
<% end %>

<%= new_page_heading do %>
  Listing Service Flow User Answer Choices
  <% if can? :create, ::ServiceFlow::UserAnswerChoice %>
    <span class="pull-right">
      <%= link_to 'New User answer choice', new_admin_service_flow_user_answer_choice_path, class: 'btn btn-primary' %>
    </span>
  <% end %>
<% end %>

<%= full_width_box_wrapper do %>
  <%= box_content_only do %>
    <div class="table-responsive">
      <%= page_datatable do %>
        <thead>
          <tr>
            <th>User</th>
            <th>Answer choice</th>
            <th>User process</th>
            <th>Actions</th>
          </tr>
        </thead>

        <tbody>
          <% @service_flow_user_answer_choices.each do |service_flow_user_answer_choice| %>
            <tr>
              <td><%= link_to service_flow_user_answer_choice.user.try(:name), [:admin, service_flow_user_answer_choice], class: 'row-link' %></td>
              <td><%= service_flow_user_answer_choice.answer_choice.try(:name) %></td>
              <td><%= service_flow_user_answer_choice.user_process.try(:name) %></td>
              <td>
                <% if can? :update, service_flow_user_answer_choice %>
                  <%= link_to 'Edit', edit_admin_service_flow_user_answer_choice_path(service_flow_user_answer_choice) %>
                <% end %>
                <% if false and can? :destroy, service_flow_user_answer_choice %> |
                  <%= link_to 'Destroy', [:admin, service_flow_user_answer_choice], method: :delete, data: { confirm: 'Are you sure?' } %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      <% end %>
    </div>
  <% end %>
<% end %>

<% content_for :javascript do %>
<script>  
  $('#dataTables-example').DataTable({
    pageLength: 25
  });
</script>
<% end %>

app/views/admin/service_flow/user_answer_choices/new.html.erb
<% content_for :breadcrumb do %>
  <%= breadcrumb_bar_new do %>
    <%= breadcrumb_item(link: admin_service_flow_user_answer_choices_path, text: 'Service Flow User Answer Choices') %>
    <%= breadcrumb_item(text: 'New') %>
  <% end %>
<% end %>

<%= new_page_heading('New Service Flow User Answer Choice') %>
<%= full_width_box_wrapper do %>
  <%= box_content_only do %>
    <%= render 'form' %>
  <% end %>
<% end %>

app/views/admin/service_flow/user_answer_choices/show.html.erb
<% content_for :breadcrumb do %>
  <%= breadcrumb_bar_new do %>
    <%= breadcrumb_item(link: admin_service_flow_user_answer_choices_path, text: 'Service Flow User Answer Choices') %>
    <%= breadcrumb_item(text: 'Service Flow User Answer Choice') %>
  <% end %>
<% end %>

<%= new_page_heading do %>
  <%= 'Service Flow User Answer Choice' %>
  <% if can? :update, @service_flow_user_answer_choice %>
    <span class="pull-right">
      <%= link_to 'Edit', edit_admin_service_flow_user_answer_choice_path, class: 'btn btn-primary btn-outline' %>
    </span>
  <% end %>
<% end %>

<%= full_width_box_wrapper do %>
  <%= box_content_only do %>
    <p class="row">
      <strong class="col-md-3 text-right">User</strong>
      <span class="col-md-9"><%= @service_flow_user_answer_choice.user.try(:name) %></span>
    </p>
    <p class="row">
      <strong class="col-md-3 text-right">Answer choice</strong>
      <span class="col-md-9"><%= @service_flow_user_answer_choice.answer_choice.try(:name) %></span>
    </p>
    <p class="row">
      <strong class="col-md-3 text-right">User process</strong>
      <span class="col-md-9"><%= @service_flow_user_answer_choice.user_process.try(:name) %></span>
    </p>
  <% end -%>
<% end -%>