config/routes.rb
Rails.application.routes.draw do
  
  # Root
  root to: 'visitors#index', as: :home

  # Devise
  devise_for :users
  devise_for :admin_users

  # User
  scope module: 'user', as: :user do
    namespace :counsel do
      resources :votes
    end # For User
    namespace :counsel do
      resources :answer_requests
    end # For User
    namespace :counsel do
      resources :answers
    end # For User
    namespace :counsel do
      resources :question_categories
    end # For User
    namespace :counsel do
      resources :questions
    end # For User
    namespace :counsel do
      resources :categories
    end # For User
    resources :global_settings # For User
    resources :reviews # For User
    resources :payment_requests # For User
    resources :customer_payments # For User
    resources :quotes # For User
    resources :carts # For User
    resources :scopes # For User
    namespace :service_flow do
      resources :user_answer_choices
    end # For User
    resources :user_processes # For User
    resources :professional_fees # For User
    resources :professional_sub_services # For User
    resources :professional_services # For User
    resources :professional_profile_edits # For User
    resources :professionals # For User
    namespace :service_flow do
      resources :answer_choices
    end # For User
    namespace :service_flow do
      resources :questions
    end # For User
    resources :scenarios # For User
    resources :sub_services # For User
    resources :services # For User
    resources :locations # For User
    get 'dashboard', to: 'dashboard#index', as: :dashboard
  end

  # Admin
  namespace :admin do
    namespace :counsel do
      resources :votes
    end # For Admin
    namespace :counsel do
      resources :answer_requests
    end # For Admin
    namespace :counsel do
      resources :answers
    end # For Admin
    namespace :counsel do
      resources :question_categories
    end # For Admin
    namespace :counsel do
      resources :questions
    end # For Admin
    namespace :counsel do
      resources :categories
    end # For Admin
    resources :global_settings # For Admin
    resources :reviews # For Admin
    resources :payment_requests # For Admin
    resources :customer_payments # For Admin
    resources :quotes # For Admin
    resources :carts # For Admin
    resources :scopes # For Admin
    namespace :service_flow do
      resources :user_answer_choices
    end # For Admin
    resources :user_processes # For Admin
    resources :professional_fees # For Admin
    resources :professional_sub_services # For Admin
    resources :professional_services # For Admin
    resources :professional_profile_edits # For Admin
    resources :professionals # For Admin
    namespace :service_flow do
      resources :answer_choices
    end # For Admin
    namespace :service_flow do
      resources :questions
    end # For Admin
    resources :scenarios # For Admin
    resources :sub_services # For Admin
    resources :services # For Admin
    resources :locations # For Admin
    get 'dashboard', to: 'dashboard#index', as: :dashboard
  end

end

app/models/counsel.rb
module Counsel
  def self.table_name_prefix
    'counsel_'
  end
end

app/models/counsel/answer.rb
class Counsel::Answer < ApplicationRecord
  belongs_to :question
  belongs_to :answerer, polymorphic: true
end

app/models/counsel/answer_request.rb
class Counsel::AnswerRequest < ApplicationRecord
  belongs_to :question
  belongs_to :requester, polymorphic: true
  belongs_to :answerer, polymorphic: true
end

app/models/counsel/category.rb
class Counsel::Category < ApplicationRecord
end

app/controllers/admin/counsel/answer_requests_controller.rb
module Admin
  class Counsel::AnswerRequestsController < ApplicationController
    before_action :set_counsel_answer_request, only: [:show, :edit, :update, :destroy]
    load_and_authorize_resource

    # GET /admin/counsel/answer_requests
    # GET /admin/counsel/answer_requests.json
    def index
      @counsel_answer_requests = ::Counsel::AnswerRequest.all
    end

    # GET /admin/counsel/answer_requests/1
    # GET /admin/counsel/answer_requests/1.json
    def show
    end

    # GET /admin/counsel/answer_requests/new
    def new
      @counsel_answer_request = ::Counsel::AnswerRequest.new
    end

    # GET /admin/counsel/answer_requests/1/edit
    def edit
    end

    # POST /admin/counsel/answer_requests
    # POST /admin/counsel/answer_requests.json
    def create
      @counsel_answer_request = ::Counsel::AnswerRequest.new(counsel_answer_request_params)

      respond_to do |format|
        if @counsel_answer_request.save
          format.html { redirect_to admin_counsel_answer_requests_url, notice: 'Answer request was successfully created.' }
          format.json { render :show, status: :created, location: admin_counsel_answer_requests_url }
        else
          format.html { render :new }
          format.json { render json: @counsel_answer_request.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /admin/counsel/answer_requests/1
    # PATCH/PUT /admin/counsel/answer_requests/1.json
    def update
      respond_to do |format|
        if @counsel_answer_request.update(counsel_answer_request_params)
          format.html { redirect_to [:admin, @counsel_answer_request], notice: 'Answer request was successfully updated.' }
          format.json { render :show, status: :ok, location: [:admin, @counsel_answer_request] }
        else
          format.html { render :edit }
          format.json { render json: @counsel_answer_request.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /admin/counsel/answer_requests/1
    # DELETE /admin/counsel/answer_requests/1.json
    def destroy
      @counsel_answer_request.destroy
      respond_to do |format|
        format.html { redirect_to admin_counsel_answer_requests_url, notice: 'Answer request was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_counsel_answer_request
        @counsel_answer_request = ::Counsel::AnswerRequest.where(id: params[:id]).first
        return invalid_access_flash_redirect_and_return if @counsel_answer_request.blank?
      end

      # Only allow a trusted parameter "white list" through.
      def counsel_answer_request_params
        default_values = {}
        params.require(:counsel_answer_request).permit(:question_id, :requester_id, :requester_type, :answerer_id, :answerer_type).merge(default_values)
      end
  end
end

app/controllers/admin/counsel/answers_controller.rb
module Admin
  class Counsel::AnswersController < ApplicationController
    before_action :set_counsel_answer, only: [:show, :edit, :update, :destroy]
    load_and_authorize_resource

    # GET /admin/counsel/answers
    # GET /admin/counsel/answers.json
    def index
      @counsel_answers = ::Counsel::Answer.all
    end

    # GET /admin/counsel/answers/1
    # GET /admin/counsel/answers/1.json
    def show
    end

    # GET /admin/counsel/answers/new
    def new
      @counsel_answer = ::Counsel::Answer.new
    end

    # GET /admin/counsel/answers/1/edit
    def edit
    end

    # POST /admin/counsel/answers
    # POST /admin/counsel/answers.json
    def create
      @counsel_answer = ::Counsel::Answer.new(counsel_answer_params)

      respond_to do |format|
        if @counsel_answer.save
          format.html { redirect_to admin_counsel_answers_url, notice: 'Answer was successfully created.' }
          format.json { render :show, status: :created, location: admin_counsel_answers_url }
        else
          format.html { render :new }
          format.json { render json: @counsel_answer.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /admin/counsel/answers/1
    # PATCH/PUT /admin/counsel/answers/1.json
    def update
      respond_to do |format|
        if @counsel_answer.update(counsel_answer_params)
          format.html { redirect_to [:admin, @counsel_answer], notice: 'Answer was successfully updated.' }
          format.json { render :show, status: :ok, location: [:admin, @counsel_answer] }
        else
          format.html { render :edit }
          format.json { render json: @counsel_answer.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /admin/counsel/answers/1
    # DELETE /admin/counsel/answers/1.json
    def destroy
      @counsel_answer.destroy
      respond_to do |format|
        format.html { redirect_to admin_counsel_answers_url, notice: 'Answer was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_counsel_answer
        @counsel_answer = ::Counsel::Answer.where(id: params[:id]).first
        return invalid_access_flash_redirect_and_return if @counsel_answer.blank?
      end

      # Only allow a trusted parameter "white list" through.
      def counsel_answer_params
        default_values = {}
        params.require(:counsel_answer).permit(:question_id, :answer, :answerer_id, :answerer_type, :accepted, :deleted).merge(default_values)
      end
  end
end

app/controllers/admin/counsel/categories_controller.rb
module Admin
  class Counsel::CategoriesController < ApplicationController
    before_action :set_counsel_category, only: [:show, :edit, :update, :destroy]
    load_and_authorize_resource

    # GET /admin/counsel/categories
    # GET /admin/counsel/categories.json
    def index
      @counsel_categories = ::Counsel::Category.all
    end

    # GET /admin/counsel/categories/1
    # GET /admin/counsel/categories/1.json
    def show
    end

    # GET /admin/counsel/categories/new
    def new
      @counsel_category = ::Counsel::Category.new
    end

    # GET /admin/counsel/categories/1/edit
    def edit
    end

    # POST /admin/counsel/categories
    # POST /admin/counsel/categories.json
    def create
      @counsel_category = ::Counsel::Category.new(counsel_category_params)

      respond_to do |format|
        if @counsel_category.save
          format.html { redirect_to admin_counsel_categories_url, notice: 'Category was successfully created.' }
          format.json { render :show, status: :created, location: admin_counsel_categories_url }
        else
          format.html { render :new }
          format.json { render json: @counsel_category.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /admin/counsel/categories/1
    # PATCH/PUT /admin/counsel/categories/1.json
    def update
      respond_to do |format|
        if @counsel_category.update(counsel_category_params)
          format.html { redirect_to [:admin, @counsel_category], notice: 'Category was successfully updated.' }
          format.json { render :show, status: :ok, location: [:admin, @counsel_category] }
        else
          format.html { render :edit }
          format.json { render json: @counsel_category.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /admin/counsel/categories/1
    # DELETE /admin/counsel/categories/1.json
    def destroy
      @counsel_category.destroy
      respond_to do |format|
        format.html { redirect_to admin_counsel_categories_url, notice: 'Category was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_counsel_category
        @counsel_category = ::Counsel::Category.where(id: params[:id]).first
        return invalid_access_flash_redirect_and_return if @counsel_category.blank?
      end

      # Only allow a trusted parameter "white list" through.
      def counsel_category_params
        default_values = {}
        params.require(:counsel_category).permit(:name).merge(default_values)
      end
  end
end

app/controllers/admin/counsel/question_categories_controller.rb
module Admin
  class Counsel::QuestionCategoriesController < ApplicationController
    before_action :set_counsel_question_category, only: [:show, :edit, :update, :destroy]
    load_and_authorize_resource

    # GET /admin/counsel/question_categories
    # GET /admin/counsel/question_categories.json
    def index
      @counsel_question_categories = ::Counsel::QuestionCategory.all
    end

    # GET /admin/counsel/question_categories/1
    # GET /admin/counsel/question_categories/1.json
    def show
    end

    # GET /admin/counsel/question_categories/new
    def new
      @counsel_question_category = ::Counsel::QuestionCategory.new
    end

    # GET /admin/counsel/question_categories/1/edit
    def edit
    end

    # POST /admin/counsel/question_categories
    # POST /admin/counsel/question_categories.json
    def create
      @counsel_question_category = ::Counsel::QuestionCategory.new(counsel_question_category_params)

      respond_to do |format|
        if @counsel_question_category.save
          format.html { redirect_to admin_counsel_question_categories_url, notice: 'Question category was successfully created.' }
          format.json { render :show, status: :created, location: admin_counsel_question_categories_url }
        else
          format.html { render :new }
          format.json { render json: @counsel_question_category.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /admin/counsel/question_categories/1
    # PATCH/PUT /admin/counsel/question_categories/1.json
    def update
      respond_to do |format|
        if @counsel_question_category.update(counsel_question_category_params)
          format.html { redirect_to [:admin, @counsel_question_category], notice: 'Question category was successfully updated.' }
          format.json { render :show, status: :ok, location: [:admin, @counsel_question_category] }
        else
          format.html { render :edit }
          format.json { render json: @counsel_question_category.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /admin/counsel/question_categories/1
    # DELETE /admin/counsel/question_categories/1.json
    def destroy
      @counsel_question_category.destroy
      respond_to do |format|
        format.html { redirect_to admin_counsel_question_categories_url, notice: 'Question category was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_counsel_question_category
        @counsel_question_category = ::Counsel::QuestionCategory.where(id: params[:id]).first
        return invalid_access_flash_redirect_and_return if @counsel_question_category.blank?
      end

      # Only allow a trusted parameter "white list" through.
      def counsel_question_category_params
        default_values = {}
        params.require(:counsel_question_category).permit(:question_id, :category_id).merge(default_values)
      end
  end
end

app/controllers/admin/counsel/questions_controller.rb
module Admin
  class Counsel::QuestionsController < ApplicationController
    before_action :set_counsel_question, only: [:show, :edit, :update, :destroy]
    load_and_authorize_resource

    # GET /admin/counsel/questions
    # GET /admin/counsel/questions.json
    def index
      @counsel_questions = ::Counsel::Question.all
    end

    # GET /admin/counsel/questions/1
    # GET /admin/counsel/questions/1.json
    def show
    end

    # GET /admin/counsel/questions/new
    def new
      @counsel_question = ::Counsel::Question.new
    end

    # GET /admin/counsel/questions/1/edit
    def edit
    end

    # POST /admin/counsel/questions
    # POST /admin/counsel/questions.json
    def create
      @counsel_question = ::Counsel::Question.new(counsel_question_params)

      respond_to do |format|
        if @counsel_question.save
          format.html { redirect_to admin_counsel_questions_url, notice: 'Question was successfully created.' }
          format.json { render :show, status: :created, location: admin_counsel_questions_url }
        else
          format.html { render :new }
          format.json { render json: @counsel_question.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /admin/counsel/questions/1
    # PATCH/PUT /admin/counsel/questions/1.json
    def update
      respond_to do |format|
        if @counsel_question.update(counsel_question_params)
          format.html { redirect_to [:admin, @counsel_question], notice: 'Question was successfully updated.' }
          format.json { render :show, status: :ok, location: [:admin, @counsel_question] }
        else
          format.html { render :edit }
          format.json { render json: @counsel_question.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /admin/counsel/questions/1
    # DELETE /admin/counsel/questions/1.json
    def destroy
      @counsel_question.destroy
      respond_to do |format|
        format.html { redirect_to admin_counsel_questions_url, notice: 'Question was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_counsel_question
        @counsel_question = ::Counsel::Question.where(id: params[:id]).first
        return invalid_access_flash_redirect_and_return if @counsel_question.blank?
      end

      # Only allow a trusted parameter "white list" through.
      def counsel_question_params
        default_values = {}
        params.require(:counsel_question).permit(:question, :description, :asker_id, :asker_type).merge(default_values)
      end
  end
end

app/views/user/counsel/answers/_form.html.erb
<%= simple_form_for([:user, @counsel_answer], wrapper: :horizontal_form, html: {class: "form-horizontal"})  do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :question %>
    <%= f.input :answer %>
    <%= f.input :accepted %>
    <%= f.input :deleted %>
  </div>

  <div class="form-actions text-center">
    <%= button_tag "Save", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/user/counsel/answers/edit.html.erb
<% content_for :breadcrumb do %>
  <%= breadcrumb_bar_new do %>
    <%= breadcrumb_item(link: user_counsel_answers_path, text: 'Counsel Answers') %>
    <%= breadcrumb_item(link: user_counsel_answer_path(@counsel_answer), text: 'Counsel Answer') %>
    <%= breadcrumb_item(text: 'Edit') %>
  <% end %>
<% end %>

<%= new_page_heading('Editing Counsel Answer') %>
<%= full_width_box_wrapper do %>
  <%= box_content_only do %>
    <%= render 'form' %>
  <% end %>
<% end %>

app/views/user/counsel/answers/index.html.erb
<% content_for :breadcrumb do %>
  <%= breadcrumb_bar_new do %>
    <%= breadcrumb_item(text: 'Counsel Answers') %>
  <% end %>
<% end %>

<%= new_page_heading do %>
  Listing Counsel Answers
  <% if can? :create, ::Counsel::Answer %>
    <span class="pull-right">
      <%= link_to 'New Answer', new_user_counsel_answer_path, class: 'btn btn-primary' %>
    </span>
  <% end %>
<% end %>

<%= full_width_box_wrapper do %>
  <%= box_content_only do %>
    <div class="table-responsive">
      <%= page_datatable do %>
        <thead>
          <tr>
            <th>Question</th>
            <th>Answer</th>
            <th>Answerer</th>
            <th>Accepted</th>
            <th>Deleted</th>
            <th>Actions</th>
          </tr>
        </thead>

        <tbody>
          <% @counsel_answers.each do |counsel_answer| %>
            <tr>
              <td><%= link_to counsel_answer.question.try(:name), [:user, counsel_answer], class: 'row-link' %></td>
              <td><%= counsel_answer.answer %></td>
              <td><%= counsel_answer.answerer.try(:name) %></td>
              <td><%= counsel_answer.accepted %></td>
              <td><%= counsel_answer.deleted %></td>
              <td>
                <% if can? :update, ::Counsel::Answer %>
                  <%= link_to 'Edit', edit_user_counsel_answer_path(counsel_answer) %>
                <% end %>
                <% if false and can? :destroy, ::Counsel::Answer %> |
                  <%= link_to 'Destroy', [:user, counsel_answer], method: :delete, data: { confirm: 'Are you sure?' } %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      <% end %>
    </div>
  <% end %>
<% end %>

<% content_for :javascript do %>
<script>  
  $('#dataTables-example').DataTable({
    pageLength: 25
  });
</script>
<% end %>

app/views/user/counsel/answers/new.html.erb
<% content_for :breadcrumb do %>
  <%= breadcrumb_bar_new do %>
    <%= breadcrumb_item(link: user_counsel_answers_path, text: 'Counsel Answers') %>
  <%= breadcrumb_item(text: 'New') %>
  <% end %>
<% end %>

<%= new_page_heading('New Counsel Answer') %>
<%= full_width_box_wrapper do %>
  <%= box_content_only do %>
    <%= render 'form' %>
  <% end %>
<% end %>

app/views/user/counsel/answers/show.html.erb
<% content_for :breadcrumb do %>
  <%= breadcrumb_bar_new do %>
    <%= breadcrumb_item(link: user_counsel_answers_path, text: 'Counsel Answer') %>
    <%= breadcrumb_item(text: 'Counsel Answer') %>
  <% end %>
<% end %>

<%= new_page_heading do %>
  <%= 'Counsel Answer' %>
  <% if can? :update, @counsel_answer %>
    <span class="pull-right">
      <%= link_to 'Edit', edit_user_counsel_answer_path, class: 'btn btn-primary btn-outline' %>
    </span>
  <% end %>
<% end %>

<%= full_width_box_wrapper do %>
  <%= box_content_only do %>
    <p class="row">
      <strong class="col-md-3 text-right">Question</strong>
      <span class="col-md-9"><%= @counsel_answer.question.try(:name) %></span>
    </p>
    <p class="row">
      <strong class="col-md-3 text-right">Answer</strong>
      <span class="col-md-9"><%= @counsel_answer.answer %></span>
    </p>
    <p class="row">
      <strong class="col-md-3 text-right">Answerer</strong>
      <span class="col-md-9"><%= @counsel_answer.answerer.try(:name) %></span>
    </p>
    <p class="row">
      <strong class="col-md-3 text-right">Accepted</strong>
      <span class="col-md-9"><%= @counsel_answer.accepted %></span>
    </p>
    <p class="row">
      <strong class="col-md-3 text-right">Deleted</strong>
      <span class="col-md-9"><%= @counsel_answer.deleted %></span>
    </p>
  <% end -%>
<% end -%>