config/routes.rb
Rails.application.routes.draw do
  
  # Root
  root to: 'visitors#index', as: :home

  # Devise
  devise_for :users
  devise_for :admin_users

  # User
  scope module: 'user', as: :user do
    namespace :counsel do
      resources :votes
    end # For User
    namespace :counsel do
      resources :answer_requests
    end # For User
    namespace :counsel do
      resources :answers
    end # For User
    namespace :counsel do
      resources :question_categories
    end # For User
    namespace :counsel do
      resources :questions
    end # For User
    namespace :counsel do
      resources :categories
    end # For User
    resources :global_settings # For User
    resources :reviews # For User
    resources :payment_requests # For User
    resources :customer_payments # For User
    resources :quotes # For User
    resources :carts # For User
    resources :scopes # For User
    namespace :service_flow do
      resources :user_answer_choices
    end # For User
    resources :user_processes # For User
    resources :professional_fees # For User
    resources :professional_sub_services # For User
    resources :professional_services # For User
    resources :professional_profile_edits # For User
    resources :professionals # For User
    namespace :service_flow do
      resources :answer_choices
    end # For User
    namespace :service_flow do
      resources :questions
    end # For User
    resources :scenarios # For User
    resources :sub_services # For User
    resources :services # For User
    resources :locations # For User
    get 'dashboard', to: 'dashboard#index', as: :dashboard
  end

  # Admin
  namespace :admin do
    namespace :counsel do
      resources :votes
    end # For Admin
    namespace :counsel do
      resources :answer_requests
    end # For Admin
    namespace :counsel do
      resources :answers
    end # For Admin
    namespace :counsel do
      resources :question_categories
    end # For Admin
    namespace :counsel do
      resources :questions
    end # For Admin
    namespace :counsel do
      resources :categories
    end # For Admin
    resources :global_settings # For Admin
    resources :reviews # For Admin
    resources :payment_requests # For Admin
    resources :customer_payments # For Admin
    resources :quotes # For Admin
    resources :carts # For Admin
    resources :scopes # For Admin
    namespace :service_flow do
      resources :user_answer_choices
    end # For Admin
    resources :user_processes # For Admin
    resources :professional_fees # For Admin
    resources :professional_sub_services # For Admin
    resources :professional_services # For Admin
    resources :professional_profile_edits # For Admin
    resources :professionals # For Admin
    namespace :service_flow do
      resources :answer_choices
    end # For Admin
    namespace :service_flow do
      resources :questions
    end # For Admin
    resources :scenarios # For Admin
    resources :sub_services # For Admin
    resources :services # For Admin
    resources :locations # For Admin
    get 'dashboard', to: 'dashboard#index', as: :dashboard
  end

end

app/models/user.rb
class User < ApplicationRecord
  
  after_initialize :set_default_role, :if => :new_record?

  enumex role: {
    customer:     [0, "Customer"], 
    professional: [1, "Professional"], 
    both:         [2, "Both"],
  }, _prefix: true

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  def set_default_role
    self.role ||= :customer
  end

  def customer?
    return (self.role_customer? or self.role_both?)
  end

  def professional?
    return (self.role_professional? or self.role_both?)
  end
end

app/controllers/admin/user_processes_controller.rb
module Admin
  class UserProcessesController < ApplicationController
    before_action :set_user_process, only: [:show, :edit, :update, :destroy]
    load_and_authorize_resource

    # GET /admin/user_processes
    # GET /admin/user_processes.json
    def index
      @user_processes = UserProcess.all
    end

    # GET /admin/user_processes/1
    # GET /admin/user_processes/1.json
    def show
    end

    # GET /admin/user_processes/new
    def new
      @user_process = UserProcess.new
    end

    # GET /admin/user_processes/1/edit
    def edit
    end

    # POST /admin/user_processes
    # POST /admin/user_processes.json
    def create
      @user_process = UserProcess.new(user_process_params)

      respond_to do |format|
        if @user_process.save
          format.html { redirect_to admin_user_processes_url, notice: 'User process was successfully created.' }
          format.json { render :show, status: :created, location: admin_user_processes_url }
        else
          format.html { render :new }
          format.json { render json: @user_process.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /admin/user_processes/1
    # PATCH/PUT /admin/user_processes/1.json
    def update
      respond_to do |format|
        if @user_process.update(user_process_params)
          format.html { redirect_to [:admin, @user_process], notice: 'User process was successfully updated.' }
          format.json { render :show, status: :ok, location: [:admin, @user_process] }
        else
          format.html { render :edit }
          format.json { render json: @user_process.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /admin/user_processes/1
    # DELETE /admin/user_processes/1.json
    def destroy
      @user_process.destroy
      respond_to do |format|
        format.html { redirect_to admin_user_processes_url, notice: 'User process was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_user_process
        @user_process = UserProcess.where(id: params[:id]).first
        return invalid_access_flash_redirect_and_return if @user_process.blank?
      end

      # Only allow a trusted parameter "white list" through.
      def user_process_params
        default_values = {}
        params.require(:user_process).permit(:id_token, :user_id, :professional_id, :service_id, :sub_service_id, :scenario_id, :status, :external_link, :started_at, :closed_at, :expected_duration).merge(default_values)
      end
  end
end

app/controllers/user/application_controller.rb
module User
  class ApplicationController < ::ApplicationController
    before_action :authenticate_user!
  end
end

app/controllers/user/carts_controller.rb
module User
  class CartsController < ApplicationController
    before_action :set_cart, only: [:show, :edit, :update, :destroy]
    load_and_authorize_resource

    # GET /user/carts
    # GET /user/carts.json
    def index
      @carts = Cart.where(user_id: current_user.id)
    end

    # GET /user/carts/1
    # GET /user/carts/1.json
    def show
    end

    # GET /user/carts/new
    def new
      @cart = Cart.new
    end

    # GET /user/carts/1/edit
    def edit
    end

    # POST /user/carts
    # POST /user/carts.json
    def create
      @cart = Cart.new(cart_params.merge(user: current_user))
      respond_to do |format|
        if @cart.save
          format.html { redirect_to user_carts_url, notice: 'Cart was successfully created.' }
          format.json { render :show, status: :created, location: user_carts_url }
        else
          format.html { render :new }
          format.json { render json: @cart.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /user/carts/1
    # PATCH/PUT /user/carts/1.json
    def update
      respond_to do |format|
        if @cart.update(cart_params)
          format.html { redirect_to [:user, @cart], notice: 'Cart was successfully updated.' }
          format.json { render :show, status: :ok, location: [:user, @cart] }
        else
          format.html { render :edit }
          format.json { render json: @cart.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /user/carts/1
    # DELETE /user/carts/1.json
    def destroy
      @cart.destroy
      respond_to do |format|
        format.html { redirect_to user_carts_url, notice: 'Cart was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_cart
        @cart = Cart.where(id: params[:id], user_id: current_user.id).first
        return invalid_access_flash_redirect_and_return if @cart.blank?
      end

      # Only allow a trusted parameter "white list" through.
      def cart_params
        default_values = {user_id: current_user.id}
        params.require(:cart).permit(:id_token, :user_process_id).merge(default_values)
      end
  end
end

app/controllers/user/counsel/answer_requests_controller.rb
module User
  class Counsel::AnswerRequestsController < ApplicationController
    before_action :set_counsel_answer_request, only: [:show, :edit, :update, :destroy]
    load_and_authorize_resource

    # GET /user/counsel/answer_requests
    # GET /user/counsel/answer_requests.json
    def index
      @counsel_answer_requests = ::Counsel::AnswerRequest.where(user_id: current_user.id)
    end

    # GET /user/counsel/answer_requests/1
    # GET /user/counsel/answer_requests/1.json
    def show
    end

    # GET /user/counsel/answer_requests/new
    def new
      @counsel_answer_request = ::Counsel::AnswerRequest.new
    end

    # GET /user/counsel/answer_requests/1/edit
    def edit
    end

    # POST /user/counsel/answer_requests
    # POST /user/counsel/answer_requests.json
    def create
      @counsel_answer_request = ::Counsel::AnswerRequest.new(counsel_answer_request_params)
      respond_to do |format|
        if @counsel_answer_request.save
          format.html { redirect_to user_counsel_answer_requests_url, notice: 'Answer request was successfully created.' }
          format.json { render :show, status: :created, location: user_counsel_answer_requests_url }
        else
          format.html { render :new }
          format.json { render json: @counsel_answer_request.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /user/counsel/answer_requests/1
    # PATCH/PUT /user/counsel/answer_requests/1.json
    def update
      respond_to do |format|
        if @counsel_answer_request.update(counsel_answer_request_params)
          format.html { redirect_to [:user, @counsel_answer_request], notice: 'Answer request was successfully updated.' }
          format.json { render :show, status: :ok, location: [:user, @counsel_answer_request] }
        else
          format.html { render :edit }
          format.json { render json: @counsel_answer_request.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /user/counsel/answer_requests/1
    # DELETE /user/counsel/answer_requests/1.json
    def destroy
      @counsel_answer_request.destroy
      respond_to do |format|
        format.html { redirect_to user_counsel_answer_requests_url, notice: 'Answer request was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_counsel_answer_request
        @counsel_answer_request = ::Counsel::AnswerRequest.where(id: params[:id], user_id: current_user.id).first
        return invalid_access_flash_redirect_and_return if @counsel_answer_request.blank?
      end

      # Only allow a trusted parameter "white list" through.
      def counsel_answer_request_params
        default_values = {user_id: current_user.id}
        params.require(:counsel_answer_request).permit(:question_id, :requester_id, :requester_type, :answerer_id, :answerer_type).merge(default_values)
      end
  end
end

app/controllers/user/counsel/answers_controller.rb
module User
  class Counsel::AnswersController < ApplicationController
    before_action :set_counsel_answer, only: [:show, :edit, :update, :destroy]
    load_and_authorize_resource

    # GET /user/counsel/answers
    # GET /user/counsel/answers.json
    def index
      @counsel_answers = ::Counsel::Answer.where(user_id: current_user.id)
    end

    # GET /user/counsel/answers/1
    # GET /user/counsel/answers/1.json
    def show
    end

    # GET /user/counsel/answers/new
    def new
      @counsel_answer = ::Counsel::Answer.new
    end

    # GET /user/counsel/answers/1/edit
    def edit
    end

    # POST /user/counsel/answers
    # POST /user/counsel/answers.json
    def create
      @counsel_answer = ::Counsel::Answer.new(counsel_answer_params)
      respond_to do |format|
        if @counsel_answer.save
          format.html { redirect_to user_counsel_answers_url, notice: 'Answer was successfully created.' }
          format.json { render :show, status: :created, location: user_counsel_answers_url }
        else
          format.html { render :new }
          format.json { render json: @counsel_answer.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /user/counsel/answers/1
    # PATCH/PUT /user/counsel/answers/1.json
    def update
      respond_to do |format|
        if @counsel_answer.update(counsel_answer_params)
          format.html { redirect_to [:user, @counsel_answer], notice: 'Answer was successfully updated.' }
          format.json { render :show, status: :ok, location: [:user, @counsel_answer] }
        else
          format.html { render :edit }
          format.json { render json: @counsel_answer.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /user/counsel/answers/1
    # DELETE /user/counsel/answers/1.json
    def destroy
      @counsel_answer.destroy
      respond_to do |format|
        format.html { redirect_to user_counsel_answers_url, notice: 'Answer was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_counsel_answer
        @counsel_answer = ::Counsel::Answer.where(id: params[:id], user_id: current_user.id).first
        return invalid_access_flash_redirect_and_return if @counsel_answer.blank?
      end

      # Only allow a trusted parameter "white list" through.
      def counsel_answer_params
        default_values = {user_id: current_user.id}
        params.require(:counsel_answer).permit(:question_id, :answer, :answerer_id, :answerer_type, :accepted, :deleted).merge(default_values)
      end
  end
end

app/controllers/user/counsel/categories_controller.rb
module User
  class Counsel::CategoriesController < ApplicationController
    before_action :set_counsel_category, only: [:show, :edit, :update, :destroy]
    load_and_authorize_resource

    # GET /user/counsel/categories
    # GET /user/counsel/categories.json
    def index
      @counsel_categories = ::Counsel::Category.where(user_id: current_user.id)
    end

    # GET /user/counsel/categories/1
    # GET /user/counsel/categories/1.json
    def show
    end

    # GET /user/counsel/categories/new
    def new
      @counsel_category = ::Counsel::Category.new
    end

    # GET /user/counsel/categories/1/edit
    def edit
    end

    # POST /user/counsel/categories
    # POST /user/counsel/categories.json
    def create
      @counsel_category = ::Counsel::Category.new(counsel_category_params)
      respond_to do |format|
        if @counsel_category.save
          format.html { redirect_to user_counsel_categories_url, notice: 'Category was successfully created.' }
          format.json { render :show, status: :created, location: user_counsel_categories_url }
        else
          format.html { render :new }
          format.json { render json: @counsel_category.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /user/counsel/categories/1
    # PATCH/PUT /user/counsel/categories/1.json
    def update
      respond_to do |format|
        if @counsel_category.update(counsel_category_params)
          format.html { redirect_to [:user, @counsel_category], notice: 'Category was successfully updated.' }
          format.json { render :show, status: :ok, location: [:user, @counsel_category] }
        else
          format.html { render :edit }
          format.json { render json: @counsel_category.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /user/counsel/categories/1
    # DELETE /user/counsel/categories/1.json
    def destroy
      @counsel_category.destroy
      respond_to do |format|
        format.html { redirect_to user_counsel_categories_url, notice: 'Category was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_counsel_category
        @counsel_category = ::Counsel::Category.where(id: params[:id], user_id: current_user.id).first
        return invalid_access_flash_redirect_and_return if @counsel_category.blank?
      end

      # Only allow a trusted parameter "white list" through.
      def counsel_category_params
        default_values = {user_id: current_user.id}
        params.require(:counsel_category).permit(:name).merge(default_values)
      end
  end
end

app/controllers/user/dashboard_controller.rb
module User
  class DashboardController < ApplicationController
    
    def index 
    end

  end
end

app/views/user/user_processes/_form.html.erb
<%= simple_form_for([:user, @user_process], wrapper: :horizontal_form, html: {class: "form-horizontal"})  do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :id_token %>
    <%= f.association :professional %>
    <%= f.association :service %>
    <%= f.association :sub_service %>
    <%= f.association :scenario %>
    <%= f.input :status %>
    <%= f.input :external_link %>
    <%= f.input :started_at %>
    <%= f.input :closed_at %>
    <%= f.input :expected_duration %>
  </div>

  <div class="form-actions text-center">
    <%= button_tag "Save", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/user/user_processes/edit.html.erb
<% content_for :breadcrumb do %>
  <%= breadcrumb_bar_new do %>
    <%= breadcrumb_item(link: user_user_processes_path, text: 'User Processes') %>
    <%= breadcrumb_item(link: user_user_process_path(@user_process), text: 'User Process') %>
    <%= breadcrumb_item(text: 'Edit') %>
  <% end %>
<% end %>

<%= new_page_heading('Editing User Process') %>
<%= full_width_box_wrapper do %>
  <%= box_content_only do %>
    <%= render 'form' %>
  <% end %>
<% end %>

app/views/user/user_processes/index.html.erb
<% content_for :breadcrumb do %>
  <%= breadcrumb_bar_new do %>
    <%= breadcrumb_item(text: 'User Processes') %>
  <% end %>
<% end %>

<%= new_page_heading do %>
  Listing User Processes
  <% if can? :create, UserProcess %>
    <span class="pull-right">
      <%= link_to 'New User process', new_user_user_process_path, class: 'btn btn-primary' %>
    </span>
  <% end %>
<% end %>

<%= full_width_box_wrapper do %>
  <%= box_content_only do %>
    <div class="table-responsive">
      <%= page_datatable do %>
        <thead>
          <tr>
            <th>Id token</th>
            <th>User</th>
            <th>Professional</th>
            <th>Service</th>
            <th>Sub service</th>
            <th>Scenario</th>
            <th>Status</th>
            <th>External link</th>
            <th>Started at</th>
            <th>Closed at</th>
            <th>Expected duration</th>
            <th>Actions</th>
          </tr>
        </thead>

        <tbody>
          <% @user_processes.each do |user_process| %>
            <tr>
              <td><%= link_to user_process.id_token, [:user, user_process], class: 'row-link' %></td>
              <td><%= user_process.user.try(:name) %></td>
              <td><%= user_process.professional.try(:name) %></td>
              <td><%= user_process.service.try(:name) %></td>
              <td><%= user_process.sub_service.try(:name) %></td>
              <td><%= user_process.scenario.try(:name) %></td>
              <td><%= user_process.status %></td>
              <td><%= user_process.external_link %></td>
              <td><%= user_process.started_at %></td>
              <td><%= user_process.closed_at %></td>
              <td><%= user_process.expected_duration %></td>
              <td>
                <% if can? :update, UserProcess %>
                  <%= link_to 'Edit', edit_user_user_process_path(user_process) %>
                <% end %>
                <% if false and can? :destroy, UserProcess %> |
                  <%= link_to 'Destroy', [:user, user_process], method: :delete, data: { confirm: 'Are you sure?' } %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      <% end %>
    </div>
  <% end %>
<% end %>

<% content_for :javascript do %>
<script>  
  $('#dataTables-example').DataTable({
    pageLength: 25
  });
</script>
<% end %>

app/views/user/user_processes/new.html.erb
<% content_for :breadcrumb do %>
  <%= breadcrumb_bar_new do %>
    <%= breadcrumb_item(link: user_user_processes_path, text: 'User Processes') %>
  <%= breadcrumb_item(text: 'New') %>
  <% end %>
<% end %>

<%= new_page_heading('New User Process') %>
<%= full_width_box_wrapper do %>
  <%= box_content_only do %>
    <%= render 'form' %>
  <% end %>
<% end %>

app/views/user/user_processes/show.html.erb
<% content_for :breadcrumb do %>
  <%= breadcrumb_bar_new do %>
    <%= breadcrumb_item(link: user_user_processes_path, text: 'User Process') %>
    <%= breadcrumb_item(text: 'User Process') %>
  <% end %>
<% end %>

<%= new_page_heading do %>
  <%= 'User Process' %>
  <% if can? :update, @user_process %>
    <span class="pull-right">
      <%= link_to 'Edit', edit_user_user_process_path, class: 'btn btn-primary btn-outline' %>
    </span>
  <% end %>
<% end %>

<%= full_width_box_wrapper do %>
  <%= box_content_only do %>
    <p class="row">
      <strong class="col-md-3 text-right">Id token</strong>
      <span class="col-md-9"><%= @user_process.id_token %></span>
    </p>
    <p class="row">
      <strong class="col-md-3 text-right">User</strong>
      <span class="col-md-9"><%= @user_process.user.try(:name) %></span>
    </p>
    <p class="row">
      <strong class="col-md-3 text-right">Professional</strong>
      <span class="col-md-9"><%= @user_process.professional.try(:name) %></span>
    </p>
    <p class="row">
      <strong class="col-md-3 text-right">Service</strong>
      <span class="col-md-9"><%= @user_process.service.try(:name) %></span>
    </p>
    <p class="row">
      <strong class="col-md-3 text-right">Sub service</strong>
      <span class="col-md-9"><%= @user_process.sub_service.try(:name) %></span>
    </p>
    <p class="row">
      <strong class="col-md-3 text-right">Scenario</strong>
      <span class="col-md-9"><%= @user_process.scenario.try(:name) %></span>
    </p>
    <p class="row">
      <strong class="col-md-3 text-right">Status</strong>
      <span class="col-md-9"><%= @user_process.status %></span>
    </p>
    <p class="row">
      <strong class="col-md-3 text-right">External link</strong>
      <span class="col-md-9"><%= @user_process.external_link %></span>
    </p>
    <p class="row">
      <strong class="col-md-3 text-right">Started at</strong>
      <span class="col-md-9"><%= @user_process.started_at %></span>
    </p>
    <p class="row">
      <strong class="col-md-3 text-right">Closed at</strong>
      <span class="col-md-9"><%= @user_process.closed_at %></span>
    </p>
    <p class="row">
      <strong class="col-md-3 text-right">Expected duration</strong>
      <span class="col-md-9"><%= @user_process.expected_duration %></span>
    </p>
  <% end -%>
<% end -%>